---
title: Mathequiz
author: Hauke Sonnenberg
date: 07.06.2025
output: xaringan::moon_reader
---

class: middle,center

# Es ist 11:45 Uhr. Wie spät ist es in einer halben Stunde?

---
class: middle,center

# 12:15 Uhr

Antwort auf die Frage:

“Es ist 11:45 Uhr. Wie spät ist es in einer halben Stunde?”

---
class: middle,center

# Was ist das Doppelte von 17?

---
class: middle,center

# 34 (= 2 ⋅ 17)

Antwort auf die Frage:

“Was ist das Doppelte von 17?”

---
class: middle,center

# Mit welchen Großbuchstaben wird die Zahl 12 als Römische Zahl geschrieben?

---
class: middle,center

# XII

Antwort auf die Frage:

“Mit welchen Großbuchstaben wird die Zahl 12 als Römische Zahl geschrieben?”

---
class: middle,center

# Wieviel Grad hat ein rechter Winkel?

---
class: middle,center

# 90 Grad

Antwort auf die Frage:

“Wieviel Grad hat ein rechter Winkel?”

---
class: middle,center

# Wieviel Grad hat ein gestreckter Winkel?

---
class: middle,center

# 180 Grad

Antwort auf die Frage:

“Wieviel Grad hat ein gestreckter Winkel?”

---
class: middle,center

# Wieviel Gramm hat ein Kilogramm?

---
class: middle,center

# 1000 g (= 1 kg)

Antwort auf die Frage:

“Wieviel Gramm hat ein Kilogramm?”

---
class: middle,center

# Wie viele Tage hat ein Jahr, das kein Schaltjahr ist?

---
class: middle,center

# 365 Tage

Antwort auf die Frage:

“Wie viele Tage hat ein Jahr, das kein Schaltjahr ist?”

---
class: middle,center

# Wenn heute Freitag ist, welcher Wochentag war vorgestern?

---
class: middle,center

# Mittwoch

Antwort auf die Frage:

“Wenn heute Freitag ist, welcher Wochentag war vorgestern?”

---
class: middle,center

# Wieviel Grad hat ein Vollwinkel?

---
class: middle,center

# 360 Grad

Antwort auf die Frage:

“Wieviel Grad hat ein Vollwinkel?”

---
class: middle,center

# Wie heißt ein Winkel, der genau 90 Grad beträgt?

---
class: middle,center

# rechter Winkel

Antwort auf die Frage:

“Wie heißt ein Winkel, der genau 90 Grad beträgt?”

---
class: middle,center

# Ist jedes Quadrat ein Rechteck?

---
class: middle,center

# Ja, ein Quadrat ist ein spezielles Rechteck

Antwort auf die Frage:

“Ist jedes Quadrat ein Rechteck?”

---
class: middle,center

# Welches Format (DIN A ?) hat ein DIN A5-Blatt, das ich in der Mitte falte?

---
class: middle,center

# DIN A6

Antwort auf die Frage:

“Welches Format (DIN A ?) hat ein DIN A5-Blatt, das ich in der Mitte falte?”

---
class: middle,center

# Ist jedes Rechteck ein Quadrat?

---
class: middle,center

# Nein

Antwort auf die Frage:

“Ist jedes Rechteck ein Quadrat?”

---
class: middle,center

# Wie viele Tage hat ein Schaltjahr?

---
class: middle,center

# 366 Tage

Antwort auf die Frage:

“Wie viele Tage hat ein Schaltjahr?”

---
class: middle,center

# Wieviel Millimeter hat ein Meter?

---
class: middle,center

# 1000 mm (= 1 m)

Antwort auf die Frage:

“Wieviel Millimeter hat ein Meter?”

---
class: middle,center

# Der Radius eines Kreises beträgt 1 Meter. Wie groß ist der Durchmesser des Kreises?

---
class: middle,center

# 2 Meter, das Doppelte des Radius

Antwort auf die Frage:

“Der Radius eines Kreises beträgt 1 Meter. Wie groß ist der Durchmesser des Kreises?”

---
class: middle,center

# Wie groß ist die Summe der Winkel in einem Dreieck?

---
class: middle,center

# 180 Grad

Antwort auf die Frage:

“Wie groß ist die Summe der Winkel in einem Dreieck?”

---
class: middle,center

# Was ist die Quersumme von 234?

---
class: middle,center

# 9

Antwort auf die Frage:

“Was ist die Quersumme von 234?”

---
class: middle,center

# Welches Format (DIN A ?) hat ein DIN A4-Blatt, das ich in der Mitte falte?

---
class: middle,center

# DIN A5

Antwort auf die Frage:

“Welches Format (DIN A ?) hat ein DIN A4-Blatt, das ich in der Mitte falte?”

---
class: middle,center

# Wenn heute Montag ist, welcher Tag ist übermorgen?

---
class: middle,center

# Mittwoch

Antwort auf die Frage:

“Wenn heute Montag ist, welcher Tag ist übermorgen?”

---
class: middle,center

# Was ist das Ergebnis von 3 ⋅ 5 + 4?

---
class: middle,center

# 19 (= 15 + 4)

Antwort auf die Frage:

“Was ist das Ergebnis von 3 ⋅ 5 + 4?”

---
class: middle,center

# Ist 13 eine Primzahl?

---
class: middle,center

# Ja, 13 ist nur durch 1 oder durch sich selbst teilbar.

Antwort auf die Frage:

“Ist 13 eine Primzahl?”

---
class: middle,center

# Wie groß ist die Summe der Winkel in einem Viereck?

---
class: middle,center

# 360 Grad

Antwort auf die Frage:

“Wie groß ist die Summe der Winkel in einem Viereck?”

---
class: middle,center

# Wie heißt ein Winkel, der genau 360 Grad beträgt?

---
class: middle,center

# Vollwinkel

Antwort auf die Frage:

“Wie heißt ein Winkel, der genau 360 Grad beträgt?”

---
class: middle,center

# Ist 33 eine Primzahl?

---
class: middle,center

# Nein, 33 ist durch 3 und 11 teilbar.

Antwort auf die Frage:

“Ist 33 eine Primzahl?”

---
class: middle,center

# Welche Zahl verbirgt sich hinter den Römischen Ziffern CL?

---
class: middle,center

# 150

Antwort auf die Frage:

“Welche Zahl verbirgt sich hinter den Römischen Ziffern CL?”

---
class: middle,center

# Was ist die Wurzel aus 81?

---
class: middle,center

# 9 (weil 9 ⋅ 9 = 81)

Antwort auf die Frage:

“Was ist die Wurzel aus 81?”

---
class: middle,center

# Welcher Buchstabe hat bei den Römischen Zahlen den Wert 100?

---
class: middle,center

# C (franz.: cent = 100)

Antwort auf die Frage:

“Welcher Buchstabe hat bei den Römischen Zahlen den Wert 100?”

---
class: middle,center

# Welcher Buchstabe wird bei den Römischen Zahlen für den Wert Tausend verwendet?

---
class: middle,center

# M (franz.: mille = 1000)

Antwort auf die Frage:

“Welcher Buchstabe wird bei den Römischen Zahlen für den Wert Tausend verwendet?”

---
class: middle,center

# Was ist das Ergebnis von 3 + 5 ⋅ 4?

---
class: middle,center

# 23 (= 3 + 20)

Antwort auf die Frage:

“Was ist das Ergebnis von 3 + 5 ⋅ 4?”

---
class: middle,center

# Was ist das Doppelte von 125?

---
class: middle,center

# 250

Antwort auf die Frage:

“Was ist das Doppelte von 125?”

---
class: middle,center

# Wie nennt man einen Winkel, der zwischen 0 und 90 Grad beträgt?

---
class: middle,center

# spitzer Winkel

Antwort auf die Frage:

“Wie nennt man einen Winkel, der zwischen 0 und 90 Grad beträgt?”

---
class: middle,center

# Welcher Buchstabe wird bei den Römischen Zahlen für den Wert 10 verwendet?

---
class: middle,center

# X (merke: zweimal V = 5 übereinander)

Antwort auf die Frage:

“Welcher Buchstabe wird bei den Römischen Zahlen für den Wert 10 verwendet?”

---
class: middle,center

# Was ist die Hälfte von 850?

---
class: middle,center

# 425

Antwort auf die Frage:

“Was ist die Hälfte von 850?”

---
class: middle,center

# Wieviel Milliliter hat ein Liter?

---
class: middle,center

# 1000 ml (= 1 l)

Antwort auf die Frage:

“Wieviel Milliliter hat ein Liter?”

---
class: middle,center

# Wie heißt ein Winkel, der genau 180 Grad beträgt?

---
class: middle,center

# gestreckter Winkel

Antwort auf die Frage:

“Wie heißt ein Winkel, der genau 180 Grad beträgt?”

---
class: middle,center

# Ich bezahle 3,85 EUR mit einem 5 EUR-Schein. Wieviel bekomme ich zurück?

---
class: middle,center

# 1,15 EUR (= 5,00 EUR - 3,85 EUR)

Antwort auf die Frage:

“Ich bezahle 3,85 EUR mit einem 5 EUR-Schein. Wieviel bekomme ich zurück?”

---
class: middle,center

# Welche Länge hat eine Stadionrunde im Olympiastadion?

---
class: middle,center

# 400 m

Antwort auf die Frage:

“Welche Länge hat eine Stadionrunde im Olympiastadion?”

---
class: middle,center

# Welcher Buchstabe wird bei den Römischen Zahlen für den Wert 5 verwendet?

---
class: middle,center

# X (merke: zweimal V = 5 übereinander)

Antwort auf die Frage:

“Welcher Buchstabe wird bei den Römischen Zahlen für den Wert 5 verwendet?”

